# Generated by Django 5.0.6 on 2024-06-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='uploads/default.jpg', null=True, upload_to='posts/media/uploads/'),
        ),
    ]
